apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y8fy0aqar-python 
  janus-idp.io/tekton: y8fy0aqar-python
  backstage.io/kubernetes-id: y8fy0aqar-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y8fy0aqar-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  