apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y8fy0aqar-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y8fy0aqar-python 
  name: y8fy0aqar-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: y8fy0aqar-python 
